# -*- coding: utf-8 -*-
"""Week 2SOH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NC0i2WyHIuYQ2f22gXSpqR7e4vNnyrWc
"""

pip install pybamm

import pybamm
import numpy as np
import matplotlib.pyplot as plt

model = pybamm.lithium_ion.SPM()
sim = pybamm.Simulation(model)
sim.solve([0, 3600])

solution = sim.solution

c_n = solution["Negative particle concentration"]

times = [0, 900, 1800, 2700, 3600]

plt.figure(figsize=(7, 5))

for t in times:

    c_rt = c_n(t=t)

    c_r = c_rt.mean(axis=1)

    r_norm = np.linspace(0, 1, len(c_r))

    plt.plot(r_norm, c_r, label=f"t = {t}s")

plt.xlabel("r / R")
plt.ylabel("Li concentration (mol m$^{-3}$)")
plt.title("Negative Particle Li Concentration")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pybamm
import numpy as np
import matplotlib.pyplot as plt

ocv_exp = pybamm.Experiment([
    "Rest for 1 minute"
])
model = pybamm.lithium_ion.SPM()

sim = pybamm.Simulation(
    model,
    experiment=ocv_exp,
    parameter_values=model.default_parameter_values
)
soc_val = np.arange(100, 0, -1)
ocv_vals = []
ocv_vals=[]
for val in soc_val:
  sim.solve(initial_soc=val/100)
  ocv = sim.solution["Battery open-circuit voltage [V]"].entries[0]
  ocv_vals.append(ocv)
plt.plot(soc_val,ocv_vals)
plt.xlabel('SOC')
plt.ylabel('OCV')

soc = soc_val/100
ocv = np.array(ocv_vals)
coeffs_5 = np.polyfit(soc, ocv, deg=5)
ocv_fit_5 = np.polyval(coeffs_5, soc)
plt.plot(soc, ocv_fit_5, label="5th order")
plt.figure(figsize=(7, 5))
plt.plot(soc, ocv_fit_5, label="5th order Poly")
plt.plot(soc, ocv_vals, label="Pybamm")
plt.xlabel('SOC')
plt.ylabel('OCV')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()